[parity]
mode = "last"
mode_timeout = 300
mode_alarm = 3600
auto_update = "critical"
release_track = "current"
public_node = false
no_download = false
no_consensus = false
no_persistent_txqueue = false

[network]
interface = "0.0.0.0"
port = 34567
min_peers = 25
max_peers = 200
nat = "any"
id = 8887
# bootnodes = ["enode://eb5b5a41cadcef38942515841e0b50bc6bf77bdf505eea78208d5605117a3bd44ebf6c2aa9548b987182d6a04ab1a208bf5bac7750be85cd6fb5d1758a8eab7b@106.75.19.197:34567"]
bootnodes = ["enode://eb5b5a41cadcef38942515841e0b50bc6bf77bdf505eea78208d5605117a3bd44ebf6c2aa9548b987182d6a04ab1a208bf5bac7750be85cd6fb5d1758a8eab7b@192.168.0.177:34567"]
discovery = true
warp = true
# private for miner, public for device, all for boot.
allow_ips = "all"
snapshot_peers = 0
max_pending_peers = 64
no_serve_light = false

[mining]
#"0xd43da923f1c1e2528eb09e9e0c9cf1024c892039"
#"0x7b4c15ab17cc4ae230ebe84f800587df1d306bc7"
#"0x2a1de6ccaa260125b764dd2f0d091106c66e919b"
#"0x3d0c31c8a7069ce31602bdeb78408781f4ecdbc8"
#"0x85614ff21a80e8043169a189018db0361dd199bb"
#"0x46f604c9f74b149aa1d120731df02ab2b5724a8d"
#"0x6963327159e5f022be28295db47ec19352a34f6e"
#"0xdc62e4c9340f8497d45841187670e953d042f083"
#"0xd38f42b94875d04a9bececf6d4f1df496604fa1d"
#"0xeb4da11a2a31b2f852d1d4d5fb7ee8a59982a9cd"

#configure both author and signer for miner.
#author = ""
#engine_signer = ""
force_sealing = true
reseal_on_txs = "all"
reseal_min_period = 4000
reseal_max_period = 60000
work_queue_size = 20
relay_set = "cheap"
usd_per_tx = "0.0025"
usd_per_eth = "auto"
price_update_period = "hourly"
gas_floor_target = "123456789"
gas_cap = "1234567890"
tx_queue_size = 8192
tx_gas_limit = "123456789"
tx_time_limit = 8000 #ms
extra_data = "Parity"
remove_solved = false
# notify_work = ["http://localhost:3001"]
refuse_service_transactions = false

[rpc]
disable = false
port = 8545
interface = "local"
cors = []
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "personal"]
hosts = ["none"]

[websockets]
disable = false
port = 8546
interface = "local"
origins = ["none"]
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "traces", "rpc", "shh", "personal"]
hosts = ["none"]

[ipc]
disable = false
path = "$HOME/.local/share/io.parity.ethereum/jsonrpc.ipc"
apis = ["web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "parity_accounts", "traces", "rpc", "shh", "personal"]

[secretstore]
disable = false
nodes = []
http_interface = "local"
http_port = 8082
interface = "local"
port = 8083
